"""Gang

Revision ID: 47943237e7bc
Revises: 8492f750636f
Create Date: 2018-11-23 19:13:32.113218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47943237e7bc'
down_revision = '8492f750636f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('breed', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('petname', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('species', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'species')
    op.drop_column('user', 'petname')
    op.drop_column('user', 'breed')
    # ### end Alembic commands ###
